name: GradleProfile

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend/compose-app

env:
  PROFILER_VERSION: 0.20.0

jobs:
  profile:
    name: "Profile Build Tasks"
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Install gradle-profiler
        uses: sdkman/sdkman-action@v1
        id: sdkman
        with:
          candidate: gradle-profiler

      - name: Run Benchmark Scenarios
        run: |
          gradle-profiler --benchmark ---scenario-file build_profile.scenarios -project-dir . cleanAssembleDemoDebug assembleDemoDebug cleanAssembleDemoRelease assembleDemoRelease

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: profile-reports
          path: './profile-out'
