name: GradleProfile

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend/compose-app

jobs:
  test_and_apk:
    name: "Local tests and APKs"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Install Gradle Profiler
        run: |
          wget https://repo1.maven.org/maven2/org/gradle/profiler/gradle-profiler/0.20.0/gradle-profiler-0.20.0.zip
          unzip gradle-profiler-0.20.0.zip -d gradle-profiler
          chmod +x gradle-profiler/bin/gradle-profiler

      - name: Run Benchmark Scenarios
        run: |
          ./gradle-profiler/bin/gradle-profiler --benchmark ---scenario-file build_profile.scenarios -project-dir . cleanAssembleDemoDebug assembleDemoDebug cleanAssembleDemoRelease assembleDemoRelease

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: profile-reports
          path: './profile-out'
